apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
  namespace: default
spec:
  secretName: my-pw-secret
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1

---
apiVersion: v1
kind: Secret
metadata:
  name: my-pw-secret
  namespace: default
type: Opaque
stringData:
  rootPassword: root123456