apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # [新增] 初始化容器：动态生成 server-id
      initContainers:
        - name: init-mysql
          image: busybox:1.28
          command:
            - sh
            - "-c"
            - |
              set -ex
              # 1. 使用 busybox 内置的 hostname 和 awk 命令提取序号
              # hostname 返回 mysql-0，awk 以 - 分割取最后一段
              ORDINAL=$(hostname | awk -F- '{print $NF}')
              echo "Detected ordinal: $ORDINAL"
              
              # 2. 计算 server-id (100 + 序号)
              # expr 是通用的数学计算工具
              SERVER_ID=$(expr 100 + $ORDINAL)
              
              # 3. 写入配置
              echo "[mysqld]" > /mnt/conf.d/server-id.cnf
              echo "server-id=$SERVER_ID" >> /mnt/conf.d/server-id.cnf
              
              # 4. 复制基础配置
              if [ -f /mnt/config-map/primary.cnf ]; then
                cp /mnt/config-map/primary.cnf /mnt/conf.d/
              fi
          volumeMounts:
            - name: conf-empty
              mountPath: /mnt/conf.d
            - name: config-map-source
              mountPath: /mnt/config-map
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root123456"
            - name: MYSQL_DATABASE
              value: "k8s_demo_db"

          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

            - name: conf-empty
              mountPath: /etc/mysql/conf.d

          # [新增] 启动探针：用于判断容器是否启动。如果失败，K8s 会重启 Pod
          startupProbe:
            exec:
              command: [ "mysqladmin", "ping", "-uroot", "-proot123456" ]
            failureThreshold: 30
            periodSeconds: 5
          # [新增] 就绪探针：用于判断服务是否可接受流量
          readinessProbe:
            exec:
              # 简单的 ping 检查，生产环境可以用更复杂的 SQL
              command: [ "mysqladmin", "ping", "-uroot", "-proot123456" ]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: config-map-source
          configMap:
            name: mysql-config
        - name: conf-empty            # 定义 1
          emptyDir: { }

  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi