apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: middleware
  labels:
    app: nacos
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
  selector:
    app: nacos

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server:v2.4.0
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: MODE
              value: "standalone"
            - name: NACOS_AUTH_ENABLE
              value: "false"
            # 【以下是新增的持久化配置】
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: MYSQL_SERVICE_HOST
              value: "mycluster.middleware.svc.cluster.local"
            - name: MYSQL_SERVICE_PORT
              value: "6446" # 注意：使用 Router 的读写端口
            - name: MYSQL_SERVICE_DB_NAME
              value: "nacos_config"
            - name: MYSQL_SERVICE_USER
              value: "root"
            - name: MYSQL_SERVICE_PASSWORD
              value: "root123456"
            - name: MYSQL_SERVICE_DB_PARAM
              value: "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
          ports:
            - containerPort: 8848
              name: server
            - containerPort: 9848
              name: client-rpc

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nacos-ingress
  namespace: middleware
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: nacos.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nacos
                port:
                  number: 8848