apiVersion: v1
kind: Service
metadata:
  name: redis-external
  namespace: middleware
spec:
  type: LoadBalancer
  selector:
    # 假设你的 Redis Pod 标签是 app=redis-cluster 或类似
    # 请先用 kubectl get pod redis-0 --show-labels 确认一下标签！
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379