apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq
  namespace: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq
  template:
    metadata:
      labels:
        app: rocketmq
    spec:
      containers:
        - name: namesrv
          image: apache/rocketmq:5.2.0
          command: [ "sh", "mqnamesrv" ]
          ports:
            - containerPort: 9876
          env:
            # 强行瘦身：限制 NameServer 内存为 256M
            - name: JAVA_OPT_EXT
              value: "-server -Xms256m -Xmx256m -Xmn128m"

        - name: broker
          image: apache/rocketmq:5.2.0
          command:
            - sh
            - -c
            - "echo 'autoCreateTopicEnable=true' > /tmp/broker.conf && sh mqbroker -n localhost:9876 -c /tmp/broker.conf"
          env:
            # 强行瘦身：限制 Broker 内存为 512M (否则默认 8G 直接炸)
            - name: JAVA_OPT_EXT
              value: "-server -Xms512m -Xmx512m -Xmn256m"

          ports:
            - containerPort: 10911
            - containerPort: 10909
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-svc
  namespace: middleware
spec:
  ports:
    - port: 9876
      name: namesrv
    - port: 10911
      name: broker
  selector:
    app: rocketmq